### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MabezDev** [MabezDev/portfolio-website#1]
#TODO

- [ ] Implement Rendering for BlogList
- [ ] Implement Rendering for ProjectList
- [ ] Implement Rendering for Blog
- [ ] Implement Rendering for Projects
